version: "3"

services:
  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}

    ports:
      - 127.0.0.1:5432:5432

    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db:/home/db
    networks:
      - network

networks:
  network:
    driver: bridge
